export interface Person {
    id: string,
    name: string,
    fatherLastName: string,
    motherLastName: string | null,
    email: string | null,
    curp: string | null,
    rfc: string | null,
    birthPlace: string | null,
    voterKey: string | null,
    gender: number | null,
    scholarship: string | null,
    profession: string | null,
    tagIDs: string[],
    ineURL: string | null,
    proofAddressURL: string | null,
    photoURL: string | null,
    phone: { number: string, isActive: boolean, } | null,
}